version: '3'

services:
  api-sales:
    build:
      context: ..
      dockerfile: api-sales/Dockerfile
    restart: always
    ports:
      - '5001:5001'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - default

networks:
  default:
    name: entrafesa-network
