version: '3'

services:
  api-sales:
    build:
      context: ..
      dockerfile: api-sales/Dockerfile
    restart: always
    ports:
      - '5001:5001'
    environment:
      - DB_PASSWORD=Jade2314
      - DB_NAME=transporte_sales
      - DB_HOST=host.docker.internal
      - DB_PORT=1433
      - DB_USER=usersql
      - PORT=5001
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=bm72psd4m18rhz1knllc
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - default

networks:
  default:
    name: entrafesa-network
