version: '3'

services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    restart: always
    ports:
      - '5000:5000'
    environment:
      - DB_PASSWORD=Jade2314
      - DB_NAME=transporte
      - DB_HOST=host.docker.internal
      - DB_PORT=1433
      - DB_USER=usersql
      - PORT=5000
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=bm72psd4m18rhz1knllc
      - JWT_SECRET=TuSecretoJWT
      - IA_API_URL=http://host.docker.internal:8000
      - IA_INTERNAL_KEY=internal-secret-key-change-in-production
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - default

networks:
  default:
    name: entrafesa-network
